### ISSUE TITLE
Cannot be statically compiled. 

### ISSUE THREAD

**Issue by Keno** [staticfloat/Nettle.jl#17]
This package actually has a good example of why we may need some more sophisticated caching for ccall. In particular, we're reading function pointers out of a struct that we need to use in ccall. I guess we can use a global variable. Interesting use case nevertheless. Currently it throws a warning that it can't be statically compiled (@vtjnash, should we disable that warning if we're not in imaging mode?). 

cc also @JeffBezanson

**Comment by staticfloat** [comment]
This should be addressed by #42
