### ISSUE TITLE
Reuse gmp dependency?

### ISSUE THREAD

**Issue by jiahao** [staticfloat/Nettle.jl#20]
I just noticed on a fresh installation on OSX 10.9.1 that Nettle pulls a homebrew bottle of gmp 5.1.3. Since gmp is a dependency of Julia itself, would it make more sense to reuse the build from Julia rather than installing a fresh copy?

**Comment by staticfloat** [comment]
I'm closing this for now, as what we have going right now seems to work.

**Comment by tkelman** [comment]
We also don't install gmp headers with `make install` or binary builds of Julia, so this wouldn't really work immediately.
