### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by randall-romero** [staticfloat/Nettle.jl#32]
Hi,

While trying to install IJulia I got an error that led me to the file scr\Nettle.jl.  In line 3 it tries to include the file ../deps/deps.jl   which I think is missing.

Thanks!

Randall

**Comment by staticfloat** [comment]
I'm going to close this for now, as I believe this issue has been dealt with.  If I am wrong, please comment here and we can reopen the issue.

**Comment by randall-romero** [comment]
Thanks, Keno and staticfloat!
