### ISSUE TITLE
don't call @eval in hash_init()

### ISSUE THREAD

**Issue by stevengj** [staticfloat/Nettle.jl#49]
The `hash_init()` function in [hash.jl](https://github.com/staticfloat/Nettle.jl/blob/34306b6a2a421f9f4276f28380a6b66369f0dcb5/src/hash.jl#L31-L100) currently calls `@eval` on a bunch of definitions.  This is a bit ugly, and it interacts badly with precompilation (`Base.compilecache(:IJulia)` generates a raft of warnings).

It seems like it would be much cleaner to simply define
```
immutable HashAlgorithm{name}
    nh::NettleHash
end
```
rather than defining a bunch of subtypes at compile-time, and then have the constructor `HashAlgorithm(name::AbstractString)` look it up at runtime to see if that hash is available.

**Comment by stevengj** [comment]
Similarly for `cipher_init()`.

**Comment by stevengj** [comment]
cc: @jakebolewski; I seem to remember we discussed this.

**Comment by staticfloat** [comment]
The question is whether we prefer to have the pointer lookups done once, at initialization, or every time someone tries to construct a hash.  I suppose lazily evaluating this would be better as most users will be interested in a small subset hashes.

**Comment by stevengj** [comment]
Exactly.  And you don't need it every time they construct a hash, only when they construct a `HashAlgorithm`, which (in cases where it matters) can easily be constructed only once (for a given algorithm) per program execution.

Moreover, if it mattered you could also have the `HashAlgorithm(::AbstractString)` function memo-ize its results in a `Dict` cache.

**Comment by staticfloat** [comment]
Closed by https://github.com/staticfloat/Nettle.jl/commit/ed4d932486b2bb5490b15f2fa894eb964459fc48
