### ISSUE TITLE
Deprecated type name `Uint8`

### ISSUE THREAD

**Issue by eschnett** [staticfloat/Nettle.jl#50]
Nettle uses the deprecated type name `Uint8` e.g. in `hmac.jl`. After the recent Julia 0.4 release branch update, I see deprecation warnings about this.

**Comment by Ken-B** [comment]
Thanks for the fix! Could you also tag a new version, so people don't have to checkout? Thanks.

**Comment by staticfloat** [comment]
A large API breakage was recently performed on this repository; as soon as I have given package authors enough time to adjust, I will tag a new version.
