### ISSUE TITLE
Release a new version.

### ISSUE THREAD

**Issue by bicycle1885** [staticfloat/Nettle.jl#55]
Could you tag and release a new version?
v0.4.0-rc2 emits massive amounts of deprecated warnings.
Since IJulia.jl depends on this package, many people would be affected.

**Comment by staticfloat** [comment]
`Nettle.jl` has recently had an API overhaul; the new API is much nicer, cleaner, and is faster to boot (in both senses of the phrase).  I have a new version pending merging into `METADATA.jl` [here](https://github.com/JuliaLang/METADATA.jl/pull/3537), but I want to give package authors that depend on `Nettle.jl`'s old API a chance to switch over gracefully.

**Comment by bicycle1885** [comment]
Great! Start-up time improvement would be significant to all users.

**Comment by tkelman** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/3537 was merged, closing
