### ISSUE TITLE
Non-sudo build option

### ISSUE THREAD

**Issue by pearcemc** [staticfloat/Nettle.jl#57]
Nettle came up as a dependency for another module (IJulia). Unfortunately I do not have sudo access in my environment, and was wondering if there was some way to install from source.

**Comment by staticfloat** [comment]
Hello @pearcemc, sorry for the late response.

You can force a from-source build of Nettle with the following snippet:
```
Pkg.add("Nettle")  # this will fail
using BinDeps
BinDeps.build("Nettle", BuildProcess)
```

This will download a tarball, compile it, and install it into a julia-specific directory.  This also works for any julia package that defines a `BuildProcess` method for building binary dependencies, [here's what it looks like](https://github.com/staticfloat/Nettle.jl/blob/ed4d932486b2bb5490b15f2fa894eb964459fc48/deps/build.jl#L28-L37) for Nettle.  Let me know if this doesn't work for you!

**Comment by staticfloat** [comment]
I am closing this, please open a new issue if troubles persist.
