### ISSUE TITLE
Nettle install "None of the selected providers can install dependency nettle."

### ISSUE THREAD

**Issue by szymmon** [staticfloat/Nettle.jl#62]
I am trying to build "Nettle" to install "IJulia", I got an error:
           
julia> Pkg.build("Nettle")
INFO: Building WinRPM
INFO: Downloading https://cache.e.ip.saba.us/http://download.opensuse.org/reposi
tories/windows:/mingw:/win32/openSUSE_13.2/repodata/repomd.xml
INFO: Downloading https://cache.e.ip.saba.us/http://download.opensuse.org/reposi
tories/windows:/mingw:/win64/openSUSE_13.2/repodata/repomd.xml
INFO: Building Nettle
INFO: Updating WinRPM package list
INFO: Downloading https://cache.e.ip.saba.us/http://download.opensuse.org/reposi
tories/windows:/mingw:/win32/openSUSE_13.2/repodata/repomd.xml
INFO: Downloading https://cache.e.ip.saba.us/http://download.opensuse.org/reposi
tories/windows:/mingw:/win64/openSUSE_13.2/repodata/repomd.xml
===============================[ ERROR: Nettle ]================================

LoadError: None of the selected providers can install dependency nettle.
Use BinDeps.debug(package_name) to see available providers

while loading C:\Users\Szymek\.julia\v0.4\Nettle\deps\build.jl, in expression st
arting on line 39

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: Nettle had build errors.

 - packages with build errors remain installed in C:\Users\Szymek\.julia\v0.4
 - build the package(s) and all dependencies with `Pkg.build("Nettle")`
 - build a single package by running its `deps/build.jl` script

================================================================================
I tried to remove and install "Ijulia" package but it didn't help, I also tried to remove https://cache.e.ip.saba.us/ from winRPM sources.list but it didn't help either.

**Comment by FrankWessels** [comment]
Same problem here. Eventually I got WinRPM to work by changing the source.list in WinRPM folder to 
ftp://anorien.csc.warwick.ac.uk/download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.1/
ftp://anorien.csc.warwick.ac.uk/download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.1/

Nettle still fails. I was hoping to find an other provider here ;/

**Comment by szymmon** [comment]
Problem solved by latest update. Pkg.update() does the trick.
