### ISSUE TITLE
Precompile failing with julia 0.6-dev

### ISSUE THREAD

**Issue by rdeits** [staticfloat/Nettle.jl#80]
Pinging @staticfloat as requested. 

I'm getting errors during precompilation of Nettle on Julia master: 

```julia
julia> using Nettle
INFO: Precompiling module Nettle.
ERROR: LoadError: UndefVarError: call not defined
Stacktrace:
 [1] _precompile_() at /Users/rdeits/.julia/v0.6/Nettle/src/precompile.jl:4
 [2] include_from_node1(::String) at ./loading.jl:539
 [3] include(::String) at ./sysimg.jl:14
 [4] anonymous at ./<missing>:2
while loading /Users/rdeits/.julia/v0.6/Nettle/src/Nettle.jl, in expression starting on line 34
ERROR: Failed to precompile Nettle to /Users/rdeits/.julia/lib/v0.6/Nettle.ji.
```

The relevant line in `precompile.jl` is:

```julia
precompile(Nettle.call, (Type{Nettle.Decryptor}, Compat.ASCIIString, Vector{UInt8},))
```

and several other lines which also attempt to precompile calls to `Nettle.call`. Presumably this is failing because `call` overloading is dropped in 0.6, although from the Travis logs it looks like this *was* working on 0.6-dev as of January. I'm not sure what's going on there. 

Switching all of the `precompile(call...` calls to 

```julia
precompile(Nettle.Decryptor, (Compat.ASCIIString, Vector{UInt8},))
```

resolves the issue. If that's the right thing to do, I'm happy to open a PR with the appropriate changes (presumably with some run-time version checking).

**Comment by staticfloat** [comment]
Sounds good to me.  I auto-generated these calls through `SnoopCompile.jl`, so as long as things work, I'm happy.  Thanks for the complete analysis, this is a great bug report.  :)

**Comment by rdeits** [comment]
Ok, thanks! I've opened #81 with the fix.
