### ISSUE TITLE
Cloning hash state

### ISSUE THREAD

**Issue by rausm** [staticfloat/Nettle.jl#89]
Hi,

I needed to copy the hashing state (avoiding recomputation for common prefixes).
Following worked well, and I'd like it to be included (IMO commonly supported functionality). 

`copy(hsh:: Hasher) = Hasher(hsh.hash_type, copy(hsh.state))`

Thanks.

edit: ping @staticfloat

**Comment by staticfloat** [comment]
Feel free to open a PR with suggestions for improvements!
