### ISSUE TITLE
Deprecation warnings, 0.6->0.7

### ISSUE THREAD

**Issue by polytomous** [staticfloat/Nettle.jl#92]
@staticfloat 
I took a shot at removing some of the deprecation warnings in Nettle for 0.7. If you'd like a diff for that, here you goooo: https://github.com/polytomous/Nettle.jl/commit/3481971abb37a9964358a67937164fb7666a61cc  

(There's one more small change after that, but you can look around yourself.) 

If you absoutely want my changes, I'll prepare a PR. Otherwise just wanted to let you know what I'd do to bring this code to the current year.

**Comment by staticfloat** [comment]
Yes please, definitely open a PR!  :)

**Comment by staticfloat** [comment]
I'm going to consider this fixed. :)
