### ISSUE TITLE
Distributed and Nettle packages are conflicting on Julia 1.1

### ISSUE THREAD

**Issue by disleyland** [staticfloat/Nettle.jl#97]
@staticfloat 

On Julia 1.1  this fails:

Using Distributed, Nettle
addprocs(1)

Error below:

fatal: error thrown and no exception handler available.
#<null>
reset_page at /Users/osx/buildbot/slave/package_osx64/build/src/gc.c:1044 [inlined]
add_page at /Users/osx/buildbot/slave/package_osx64/build/src/gc.c:1080
jl_gc_pool_alloc at /Users/osx/buildbot/slave/package_osx64/build/src/gc.c:1142
Type at ./iobuffer.jl:20 [inlined]
Type at ./iobuffer.jl:27 [inlined]
#IOBuffer#303 at ./iobuffer.jl:98
Type at ./none:0 [inlined]
#IOBuffer#304 at ./iobuffer.jl:114
Type at ./none:0 [inlined]
#print_to_string#330 at ./strings/io.jl:116
print_to_string at ./strings/io.jl:112 [inlined]
string at ./strings/io.jl:143 [inlined]
__init__ at ./sysinfo.jl:114
jl_apply at /Users/osx/buildbot/slave/package_osx64/build/src/./julia.h:1571 [inlined]
jl_module_run_initializer at /Users/osx/buildbot/slave/package_osx64/build/src/toplevel.c:72
_julia_init at /Users/osx/buildbot/slave/package_osx64/build/src/init.c:832
main at /Applications/Julia-1.1.app/Contents/Resources/julia/bin/julia (unknown line)
ERROR: Unable to read host:port string from worker. Launch command exited with error?
error(::String) at ./error.jl:33
read_worker_host_port(::Base.PipeEndpoint) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Distributed/src/cluster.jl:275
connect(::Distributed.LocalManager, ::Int64, ::WorkerConfig) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Distributed/src/managers.jl:397
create_worker(::Distributed.LocalManager, ::WorkerConfig) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Distributed/src/cluster.jl:501
setup_launched_worker(::Distributed.LocalManager, ::WorkerConfig, ::Array{Int64,1}) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Distributed/src/cluster.jl:447
(::getfield(Distributed, Symbol("##47#50")){Distributed.LocalManager,WorkerConfig})() at ./task.jl:259
Stacktrace:
 [1] sync_end(::Array{Any,1}) at ./task.jl:226
 [2] macro expansion at ./task.jl:245 [inlined]
 [3] #addprocs_locked#44(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Distributed.LocalManager) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Distributed/src/cluster.jl:401
 [4] addprocs_locked at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Distributed/src/cluster.jl:372 [inlined]
 [5] #addprocs#43(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Distributed.LocalManager) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Distributed/src/cluster.jl:365
 [6] addprocs at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Distributed/src/cluster.jl:359 [inlined]
 [7] #addprocs#255 at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Distributed/src/managers.jl:316 [inlined]
 [8] addprocs(::Int64) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Distributed/src/managers.jl:315
 [9] top-level scope at none:0

**Comment by staticfloat** [comment]
Interesting; I am inclined to think that this is not a `Nettle` issue, but rather something wrong with `Distributed` or something else in your system.  If you do not `using Nettle`, does the issue still occur?

**Comment by disleyland** [comment]
Hi

Brand new installation. Without nettle its fine. But with it fails. Ill try yet another install and see if same thing persists

**Comment by disleyland** [comment]
Hi,  yes very strange, something in my system, as i tried a different mac and ubuntu and was fine there.  but for the life of me i can't figure out what and the error doesn't lead me to it.  I've clean out v1.1 from the environments folder and compiled. replaced the julia 1.1 package with new download, and installed just Nettle so its the only package available, same problem.  Any tips on what else do i need to remove to get a true clean uninstall?

**Comment by staticfloat** [comment]
When you run `addprocs(1)`, it launches a second process of Julia, and that second process seems to be dying, so let's figure out if we can discover what the command being used to launch that second process of Julia is.

I think the most likely explanation is that there is some other `libnettle` or something that the second Julia process is picking up.  Can you use `ps aux` to see the launch commands of `julia` just as it gets launched, but before it dies?  That's probably the simplest way to see it without recompiling Julia (if you are able to recompile, we just want to see [what `cmd` is here](https://github.com/JuliaLang/julia/blob/release-1.1/stdlib/Distributed/src/managers.jl#L328).

**Comment by disleyland** [comment]
Ok i've figured out the problem by comparing a completely new 1.1 setup with only Nettle added, to my pre-existing configuration.  when Nettle was added on a new 1.1 BUT within a preexisting 1.0+ environment, the nettle build used a pre-existing and seemingly incompatible BinaryProvider package i had installed earlier on a Julia 1.0 config. So while in the package status, i thought i had the latest [49dea1ee] Nettle v.0.4.0 installed, i didn't have the latest of everything needed.  i just updated BinaryProvider and and rebuilt both, and now addprocs works.  The question remains, what in an older Julia 1.0 BinaryProvider package breaks what Nettle requires and how can a Nettle package add ensure its got the right BinaryProvider?

**Comment by staticfloat** [comment]
Ah, interesting.  I didn't realize that an older `Nettle` version could cause things to break so badly.

The `upgrade` command put into the `pkg> ` prompt should fix this in the future.
