### ISSUE TITLE
A compat section is missing as well as Project file.

### ISSUE THREAD

**Issue by akels** [staticfloat/Nettle.jl#99]
Currently, AutoMerge complains about this package does not have a [compat] section. It seems that project files are also not existent. 

@staticfloat is there a reason for not having a project file at this moment?

**Comment by staticfloat** [comment]
Nope! Just never got around to it, I guess.  Feel free to open a PR creating one (make sure the UUID is the same as the auto-assigned one from the `General` registry).

**Comment by akels** [comment]
Ok. I will look into that in weekend.
